### ISSUE TITLE
"Ghost rooms" returned by get_dm_rooms raising LocalProtocolError

### ISSUE THREAD

**Issue by fvjosef21** [nexy7574/nio-bot#13]
**Is your feature request related to a problem? Please describe.**
get_dm_rooms returns a list of rooms. However, this list may be stale (since a user may have left the room, forget room, or ?).
This leads to the bug that trying to connect to the room will lead to a LocalProtocolError
```
Error: LocalProtocolError('No such room with id !NBwtLCgGNCdtVfASwf:[matrix.org](http://matrix.org/) found.')
```

At the moment, we picked the first room returned by `get_dm_rooms` in `send_message`. I suggested to use the last room, since it looked like the newest rooms were at the end of the list, but now I am not sure if that is actually true (it may depend on the specific matrix server).

**Describe the solution you'd like**
First of. I am a beginner in Matrix, so take the following with a grain of salt. I don't understand the difference between a DM room and a room that has two users with a visibility of "invite only".

`MatrixRoom` in matrix-nio has a dict for users and visibility. So I guess we can check if the correct two users are in that room and if the `visbility` and maybe `history_visibility` is set correctly. Then filter out the rooms that do not match these criteria.

**Describe alternatives you've considered**

No idea what else we can do.

**Additional context**
Changing the room to the last seems to work for me, but now I have a problem that every message from the bot creates a new room.

**Comment by nexy7574** [comment]
Context that has been discussed in the [matrix room](https://nio-bot.dev/support):

* `get_dm_rooms` was returning rooms that included rooms that no-longer existed, or were invalid for some other reason
* By checking the returned room IDs against those in `niobot.NioBot.rooms`, it can be more accurately determined which rooms exist
* `send_message` should first check against `rooms` to see if the room is valid, throwing an error preemptively if a room is invalid

**Comment by nexy7574** [comment]
watching https://github.com/matrix-org/matrix-js-sdk/issues/2672, related

**Comment by nexy7574** [comment]
Issue directly relates to #15
